/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scoalasoferi;

import java.awt.Component;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author katy
 */
public class BDJFrame extends javax.swing.JFrame {

    /**
     * Creates new form BDJFrame
     */
    javax.swing.GroupLayout lay=new javax.swing.GroupLayout(getContentPane());
    
    public BDJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        Cursant = new javax.swing.JMenu();
        vizualiareCursant = new javax.swing.JMenuItem();
        AddCursant = new javax.swing.JMenuItem();
        StergereCursant = new javax.swing.JMenuItem();
        Instructor = new javax.swing.JMenu();
        VizualizareInstructor = new javax.swing.JMenuItem();
        AddInstructor = new javax.swing.JMenuItem();
        StergereInstructor = new javax.swing.JMenuItem();
        Masina = new javax.swing.JMenu();
        VizualizareMasina = new javax.swing.JMenuItem();
        AddMasina = new javax.swing.JMenuItem();
        StergereMasina = new javax.swing.JMenuItem();
        Fisa = new javax.swing.JMenu();
        VizualizareFisa = new javax.swing.JMenuItem();
        AddFisa = new javax.swing.JMenuItem();
        StergereFisa = new javax.swing.JMenuItem();
        Rezultat = new javax.swing.JMenu();
        VizualizareRezultat = new javax.swing.JMenuItem();
        AddRezultat = new javax.swing.JMenuItem();
        StergereRezultat = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        jMenuItem7.setText("jMenuItem7");

        jMenuItem16.setText("jMenuItem16");

        jMenuItem20.setText("jMenuItem20");

        jMenuItem24.setText("jMenuItem24");

        jMenuItem28.setText("jMenuItem28");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Cursant.setText("Cursant");
        Cursant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CursantActionPerformed(evt);
            }
        });

        vizualiareCursant.setText("Vizualizare");
        vizualiareCursant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vizualiareCursantActionPerformed(evt);
            }
        });
        Cursant.add(vizualiareCursant);

        AddCursant.setText("Adaugare");
        AddCursant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCursantActionPerformed(evt);
            }
        });
        Cursant.add(AddCursant);

        StergereCursant.setText("Stergere");
        StergereCursant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StergereCursantActionPerformed(evt);
            }
        });
        Cursant.add(StergereCursant);

        jMenuBar1.add(Cursant);

        Instructor.setText("Instructor");

        VizualizareInstructor.setText("Vizualizare");
        VizualizareInstructor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VizualizareInstructorActionPerformed(evt);
            }
        });
        Instructor.add(VizualizareInstructor);

        AddInstructor.setText("Adaugare");
        AddInstructor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddInstructorActionPerformed(evt);
            }
        });
        Instructor.add(AddInstructor);

        StergereInstructor.setText("Stergere");
        StergereInstructor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StergereInstructorActionPerformed(evt);
            }
        });
        Instructor.add(StergereInstructor);

        jMenuBar1.add(Instructor);

        Masina.setText("Masina");

        VizualizareMasina.setText("Vizualizare");
        VizualizareMasina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VizualizareMasinaActionPerformed(evt);
            }
        });
        Masina.add(VizualizareMasina);

        AddMasina.setText("Adaugare");
        AddMasina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddMasinaActionPerformed(evt);
            }
        });
        Masina.add(AddMasina);

        StergereMasina.setText("Stergere");
        StergereMasina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StergereMasinaActionPerformed(evt);
            }
        });
        Masina.add(StergereMasina);

        jMenuBar1.add(Masina);

        Fisa.setText("FisaService");

        VizualizareFisa.setText("Vizualizare");
        VizualizareFisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VizualizareFisaActionPerformed(evt);
            }
        });
        Fisa.add(VizualizareFisa);

        AddFisa.setText("Adaugare");
        AddFisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFisaActionPerformed(evt);
            }
        });
        Fisa.add(AddFisa);

        StergereFisa.setText("Stergere");
        StergereFisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StergereFisaActionPerformed(evt);
            }
        });
        Fisa.add(StergereFisa);

        jMenuBar1.add(Fisa);

        Rezultat.setText("Rezultat");

        VizualizareRezultat.setText("Vizualizare");
        VizualizareRezultat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VizualizareRezultatActionPerformed(evt);
            }
        });
        Rezultat.add(VizualizareRezultat);

        AddRezultat.setText("Adaugare");
        AddRezultat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddRezultatActionPerformed(evt);
            }
        });
        Rezultat.add(AddRezultat);

        StergereRezultat.setText("Stergere");
        StergereRezultat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StergereRezultatActionPerformed(evt);
            }
        });
        Rezultat.add(StergereRezultat);

        jMenuBar1.add(Rezultat);

        jMenu1.setText("Selecturi");

        jMenuItem5.setText("1.Selectati numele si prenumele cursantilor care au instructorul cu numele \"Ionescu\",ordonati crescator dupa nume.");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem6.setText("2.Afisati numarul si marca masinilor care au circulat pe saptamana un numar de ore mai mare de 30.");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem8.setText("3.Aflati numarul de cursanti pentru fiecare instructor.");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuItem9.setText("4.Aflati numarul si marca masinii care a avut cele mai multe interventii in anul 2010.");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem9);

        jMenuItem10.setText("5.Afisati numele,prenumele si salariul instructorilor care au mers minim 10 ore pe saptamana cu masina Cielo.");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem10);

        jMenuItem11.setText("6.Pentru fiecare masina selectati numarul cursantilor care o conduc.");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem11);

        jMenuItem12.setText("7.Afisati numarul de cursanti admisi si numarul de cursanti respinsi pentru fiecare an.");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem12);

        jMenuItem13.setText("8. Sa se determine numele si prenumele instructorilor care au categoria A sau B si conduc minim 40 ore/saptamana.");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem13);

        jMenuItem14.setText("9.In ce an s-au inscris cei mai multi cursanti ? ");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem14);

        jMenuItem15.setText("11. Gasiti numele,prenumele,categoria, si salariul instructorilor care au cursanti admisi.");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem15);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 424, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 263, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vizualiareCursantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vizualiareCursantActionPerformed
        // TODO add your handling code here:
        
        getContentPane().setLayout(lay);
        if(lastComponent!=null){
        lay.replace(lastComponent,cursant);
        }
        lastComponent=cursant;
        lay.setHorizontalGroup(
            lay.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cursant, javax.swing.GroupLayout.DEFAULT_SIZE,200, Short.MAX_VALUE)
        );
        lay.setVerticalGroup(
            lay.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cursant, javax.swing.GroupLayout.DEFAULT_SIZE,200, Short.MAX_VALUE)
        );
        
        
        
    }//GEN-LAST:event_vizualiareCursantActionPerformed

    private void AddCursantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCursantActionPerformed
        // TODO add your handling code here:
        JFrame adaugaCursant=new AdaugareCursant();
        adaugaCursant.setVisible(true);
        adaugaCursant.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_AddCursantActionPerformed

    private void StergereCursantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StergereCursantActionPerformed
        // TODO add your handling code here:
        //System.out.println(cursant.getRow());
        comunicatie cm=new comunicatie();
               try {
                 System.out.println("DELETE from Cursant where idcursant="+cursant.getId());
                         cm.execute("DELETE from Cursant where idcursant="+cursant.getId());
               } catch (SQLException ex) {
                   System.out.println(ex);
               }
         cursant.update();
        
    }//GEN-LAST:event_StergereCursantActionPerformed

    private void CursantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CursantActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CursantActionPerformed

    private void AddInstructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddInstructorActionPerformed
        // TODO add your handling code here:
        JFrame adaugaInstructor=new AdaugaInstructor();
        adaugaInstructor.setVisible(true);
        adaugaInstructor.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_AddInstructorActionPerformed

    private void AddMasinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddMasinaActionPerformed
        // TODO add your handling code here:
        JFrame adaugaMasina=new Masina();
        adaugaMasina.setVisible(true);
        adaugaMasina.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_AddMasinaActionPerformed

    private void AddFisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFisaActionPerformed
        // TODO add your handling code here:
        JFrame adaugaFisa=new AdaugaFisa(masina.getId());
        adaugaFisa.setVisible(true);
        adaugaFisa.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_AddFisaActionPerformed

    private void AddRezultatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddRezultatActionPerformed
        // TODO add your handling code here:
         JFrame adaugaRezultat=new AdaugaRezultat(cursant.getId());
        adaugaRezultat.setVisible(true);
        adaugaRezultat.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_AddRezultatActionPerformed

    private void VizualizareInstructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VizualizareInstructorActionPerformed
        // TODO add your handling code here:
         getContentPane().setLayout(lay);
        if(lastComponent!=null){
        lay.replace(lastComponent, instructor);
        }
        lastComponent=instructor;
        
        lay.setHorizontalGroup(
            lay.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(instructor, javax.swing.GroupLayout.DEFAULT_SIZE,200, Short.MAX_VALUE)
        );
        lay.setVerticalGroup(
            lay.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(instructor, javax.swing.GroupLayout.DEFAULT_SIZE,200, Short.MAX_VALUE)
        ); 
    }//GEN-LAST:event_VizualizareInstructorActionPerformed

    private void VizualizareMasinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VizualizareMasinaActionPerformed
        // TODO add your handling code here:
        System.out.println("Test");
        getContentPane().setLayout(lay);
        if(lastComponent!=null){
        lay.replace(lastComponent,masina);
        }
        lastComponent=masina;
        
        lay.setHorizontalGroup(
            lay.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(masina, javax.swing.GroupLayout.DEFAULT_SIZE,200, Short.MAX_VALUE)
        );
        lay.setVerticalGroup(
            lay.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(masina, javax.swing.GroupLayout.DEFAULT_SIZE,200, Short.MAX_VALUE)
        );
    }//GEN-LAST:event_VizualizareMasinaActionPerformed

    private void VizualizareFisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VizualizareFisaActionPerformed
        // TODO add your handling code here:
        System.out.println("Test");
        getContentPane().setLayout(lay);
       if(lastComponent!=null){
        lay.replace(lastComponent,fisa);
        }
        lastComponent=fisa;
        lay.setHorizontalGroup(
            lay.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fisa, javax.swing.GroupLayout.DEFAULT_SIZE,200, Short.MAX_VALUE)
        );
        lay.setVerticalGroup(
            lay.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fisa, javax.swing.GroupLayout.DEFAULT_SIZE,200, Short.MAX_VALUE)
        );
    }//GEN-LAST:event_VizualizareFisaActionPerformed

    private void VizualizareRezultatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VizualizareRezultatActionPerformed
        // TODO add your handling code here:
        System.out.println("Test");
        getContentPane().setLayout(lay);
        if(lastComponent!=null){
        lay.replace(lastComponent,rezultat);
        }
        lastComponent=rezultat;
        lay.setHorizontalGroup(
            lay.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rezultat, javax.swing.GroupLayout.DEFAULT_SIZE,200, Short.MAX_VALUE)
        );
        lay.setVerticalGroup(
            lay.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rezultat, javax.swing.GroupLayout.DEFAULT_SIZE,200, Short.MAX_VALUE)
        );
    }//GEN-LAST:event_VizualizareRezultatActionPerformed

    private void StergereInstructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StergereInstructorActionPerformed
        // TODO add your handling code here:
        comunicatie cm=new comunicatie();
               try {
                 System.out.println("DELETE from Instructor where idinstructor="+instructor.getId());
                         cm.execute("DELETE from instructor where idinstructor="+instructor.getId());
               } catch (SQLException ex) {
                   System.out.println(ex);
               }
         instructor.update();
    }//GEN-LAST:event_StergereInstructorActionPerformed

    private void StergereMasinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StergereMasinaActionPerformed
        // TODO add your handling code here:
          comunicatie cm=new comunicatie();
               try {
                 System.out.println("DELETE from masina where idmasina="+masina.getId());
                         cm.execute("DELETE from masina where idmasina="+masina.getId());
               } catch (SQLException ex) {
                   System.out.println(ex);
               }
         masina.update();
        
    }//GEN-LAST:event_StergereMasinaActionPerformed

    private void StergereFisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StergereFisaActionPerformed
        // TODO add your handling code here:
        comunicatie cm=new comunicatie();
               try {
                 System.out.println("DELETE from fisaservice where idfisa="+fisa.getId());
                         cm.execute("DELETE from fisaservice where idfisa="+fisa.getId());
               } catch (SQLException ex) {
                   System.out.println(ex);
               }
         fisa.update();
    }//GEN-LAST:event_StergereFisaActionPerformed

    private void StergereRezultatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StergereRezultatActionPerformed
        // TODO add your handling code here:
        comunicatie cm=new comunicatie();
               try {
                 System.out.println("DELETE from rezultat where idrezultate="+rezultat.getId());
                         cm.execute("DELETE from rezultat where idrezultate="+rezultat.getId());
               } catch (SQLException ex) {
                   System.out.println(ex);
               }
         rezultat.update();
    }//GEN-LAST:event_StergereRezultatActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
         r3 r=new r3();
        r.setVisible(true);
        r.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
         r6 r=new r6();
        r.setVisible(true);
        r.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
         r8 r=new r8();
        r.setVisible(true);
        r.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        r1 r=new r1();
        r.setVisible(true);
        r.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
         r2 r=new r2();
        r.setVisible(true);
        r.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
         r4 r=new r4();
        r.setVisible(true);
        r.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
         r5 r=new r5();
        r.setVisible(true);
        r.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
         r7 r=new r7();
        r.setVisible(true);
        r.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
         r9 r=new r9();
        r.setVisible(true);
        r.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
         r10 r=new r10();
        r.setVisible(true);
        r.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BDJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BDJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BDJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BDJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BDJFrame().setVisible(true);
            }
        });
    }
    public void getID(){}
    
    public VMasina masina=new VMasina();
    public Instructor instructor=new Instructor();
    public Rezultat rezultat=new Rezultat();
    public Cursant cursant=new Cursant();
    public Fisa fisa=new Fisa();
    Component lastComponent=null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AddCursant;
    private javax.swing.JMenuItem AddFisa;
    private javax.swing.JMenuItem AddInstructor;
    private javax.swing.JMenuItem AddMasina;
    private javax.swing.JMenuItem AddRezultat;
    private javax.swing.JMenu Cursant;
    private javax.swing.JMenu Fisa;
    private javax.swing.JMenu Instructor;
    private javax.swing.JMenu Masina;
    private javax.swing.JMenu Rezultat;
    private javax.swing.JMenuItem StergereCursant;
    private javax.swing.JMenuItem StergereFisa;
    private javax.swing.JMenuItem StergereInstructor;
    private javax.swing.JMenuItem StergereMasina;
    private javax.swing.JMenuItem StergereRezultat;
    private javax.swing.JMenuItem VizualizareFisa;
    private javax.swing.JMenuItem VizualizareInstructor;
    private javax.swing.JMenuItem VizualizareMasina;
    private javax.swing.JMenuItem VizualizareRezultat;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem vizualiareCursant;
    // End of variables declaration//GEN-END:variables
}
